"""
Django settings for Proyectoweb project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*#@p1b#mx55zga97cmy=qoziqkr+-49ert_e+@l^hh0f5cm5mh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ProyectoWebApp',
    'servicios',
    'blog',
    'contacto',
    'tienda',
    'carro',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Proyectoweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #Los procesadores de contexto nuevos se ponene desde aqui:######################################
                'carro.context_processor.importe_total_carro',
            ],
        },
    },
]

WSGI_APPLICATION = 'Proyectoweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'es-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

#Debido a nuestro modelo servicios que tiene un campo tipo imagen las imagenes se guardan fuera del proyecto y queda desordenado
#Para solucioonar esto se creo una carpeta media y se indicara tambien eso en aqui settings

MEDIA_URL='/media/'  #Aqui especificamos la url publica que aparecera en la barra del navegador, eesto sirve para si por ejemplo algun usario hace clcik en una imagen redireccionara a esta url 
#para mostrar dicha imagen, para hacer esto debemos especificar esta url tambien en urls.py (NOTA: Para ver una imagen del navegador normalmnete se da antiolick y ver en nueva pestaña)
MEDIA_ROOT=BASE_DIR / 'media' #Aqui especifacmos donde buscara los archivos multimedia

#Esta parte la haremos para la configuración de e-mail, para que nos mande lo que se envio desde el form de la app Contacto 
EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST="smtp.gmail.com"
EMAIL_USE_TLS=True
EMAIL_PORT=587
EMAIL_HOST_USER="XXXX@XXXX.com" #Aqui debe ir un correo valido que servira de host, cualquier correo (con la data llenada en el 
# formulario) que se envie, se enviara DESDE AQUI y se copiara a este mismo correo. 
EMAIL_HOST_PASSWORD="XXXXXX"#Django debe tener acceso a dicho correo por lo que aqui se debe poner la contraseña con la que se accede a ese correo
#Pasos para configurar el gmail como host:
#1.apretar imagen
#2.administrartu vuenta de google
#3. entrar a seguridad
#4. Acceso de aplicaciones poco seguras
#5. Activar opcion