# Generated by Django 3.1.2 on 2021-05-25 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20210524_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='prrecio',
            new_name='precio',
        ),
    ]
